"""Column lists for remaining compras.gov list endpoints."""

CONTRATACAO_PK = ("id_compra",)
CONTRATACAO_COLUMNS = (
    "id_compra",
    "numero_controle_pncp",
    "ano_compra_pncp",
    "sequencial_compra_pncp",
    "orgao_entidade_cnpj",
    "orgao_subrogado_cnpj",
    "codigo_orgao",
    "orgao_entidade_razao_social",
    "orgao_subrogado_razao_social",
    "orgao_entidade_esfera_id",
    "orgao_subrogado_esfera_id",
    "orgao_entidade_poder_id",
    "orgao_subrogado_poder_id",
    "unidade_orgao_codigo_unidade",
    "unidade_subrogada_codigo_unidade",
    "unidade_orgao_nome_unidade",
    "unidade_subrogada_nome_unidade",
    "unidade_orgao_uf_sigla",
    "unidade_subrogada_uf_sigla",
    "unidade_orgao_municipio_nome",
    "unidade_subrogada_municipio_nome",
    "unidade_orgao_codigo_ibge",
    "unidade_subrogada_codigo_ibge",
    "numero_compra",
    "modalidade_id_pncp",
    "codigo_modalidade",
    "modalidade_nome",
    "srp",
    "modo_disputa_id_pncp",
    "codigo_modo_disputa",
    "amparo_legal_codigo_pncp",
    "amparo_legal_nome",
    "amparo_legal_descricao",
    "informacao_complementar",
    "processo",
    "objeto_compra",
    "existe_resultado",
    "orcamento_sigiloso_codigo",
    "orcamento_sigiloso_descricao",
    "situacao_compra_id_pncp",
    "situacao_compra_nome_pncp",
    "tipo_instrumento_convocatorio_codigo_pncp",
    "tipo_instrumento_convocatorio_nome",
    "modo_disputa_nome_pncp",
    "valor_total_estimado",
    "valor_total_homologado",
    "data_inclusao_pncp",
    "data_atualizacao_pncp",
    "data_publicacao_pncp",
    "data_abertura_proposta_pncp",
    "data_encerramento_proposta_pncp",
    "contratacao_excluida",
)

CONTRATACAO_ITEM_PK = ("id_compra", "id_compra_item")
CONTRATACAO_ITEM_COLUMNS = (
    "id_compra",
    "id_compra_item",
    "id_contratacao_pncp",
    "unidade_orgao_codigo_unidade",
    "orgao_entidade_cnpj",
    "numero_item_pncp",
    "numero_item_compra",
    "numero_grupo",
    "descricao_resumida",
    "material_ou_servico",
    "material_ou_servico_nome",
    "codigo_classe",
    "codigo_grupo",
    "cod_item_catalogo",
    "descricaodetalhada",
    "unidade_medida",
    "orcamento_sigiloso",
    "item_categoria_id_pncp",
    "item_categoria_nome",
    "criterio_julgamento_id_pncp",
    "criterio_julgamento_nome",
    "situacao_compra_item",
    "situacao_compra_item_nome",
    "tipo_beneficio",
    "tipo_beneficio_nome",
    "incentivo_produtivo_basico",
    "quantidade",
    "valor_unitario_estimado",
    "valor_total",
    "tem_resultado",
    "cod_fornecedor",
    "nome_fornecedor",
    "quantidade_resultado",
    "valor_unitario_resultado",
    "valor_total_resultado",
    "data_inclusao_pncp",
    "data_atualizacao_pncp",
    "data_resultado",
    "margem_preferencia_normal",
    "percentual_margem_preferencia_normal",
    "margem_preferencia_adicional",
    "percentual_margem_preferencia_adicional",
    "codigo_ncm",
    "descricao_ncm",
    "numero_controle_pncp_compra",
    "codigo_pdm",
    "nome_pdm",
)

CONTRATACAO_RESULTADO_PK = ("id_compra", "id_compra_item", "sequencial_resultado")
CONTRATACAO_RESULTADO_COLUMNS = (
    "id_compra_item",
    "id_compra",
    "id_contratacao_pncp",
    "unidade_orgao_codigo_unidade",
    "unidade_orgao_uf_sigla",
    "numero_item_pncp",
    "sequencial_resultado",
    "ni_fornecedor",
    "tipo_pessoa",
    "nome_razao_social_fornecedor",
    "codigo_pais",
    "indicador_subcontratacao",
    "ordem_classificacao_srp",
    "quantidade_homologada",
    "valor_unitario_homologado",
    "valor_total_homologado",
    "percentual_desconto",
    "situacao_compra_item_resultado_id",
    "situacao_compra_item_resultado_nome",
    "motivo_cancelamento",
    "porte_fornecedor_id",
    "porte_fornecedor_nome",
    "natureza_juridica_nome",
    "natureza_juridica_id",
    "data_inclusao_pncp",
    "data_atualizacao_pncp",
    "data_cancelamento_pncp",
    "data_resultado_pncp",
    "numero_controle_pncp_compra",
    "orgao_entidade_cnpj",
    "aplicacao_margem_preferencia",
    "amparo_legal_margem_preferencia_id",
    "amparo_legal_margem_preferencia_nome",
    "aplicacao_beneficio_meepp",
    "aplicacao_criterio_desempate",
    "amparo_legal_criterio_desempate_id",
    "amparo_legal_criterio_desempate_nome",
    "moeda_estrangeira_id",
    "data_cotacao_moeda_estrangeira",
    "valor_nominal_moeda_estrangeira",
    "pais_origem_produto_servico_id",
    "timezone_cotacao_moeda_estrangeira",
)

ARP_PK = ("numero_controle_pncp_ata",)
ARP_COLUMNS = (
    "numero_ata_registro_preco",
    "codigo_unidade_gerenciadora",
    "nome_unidade_gerenciadora",
    "codigo_orgao",
    "nome_orgao",
    "link_ata_pncp",
    "link_compra_pncp",
    "numero_compra",
    "ano_compra",
    "codigo_modalidade_compra",
    "nome_modalidade_compra",
    "data_assinatura",
    "data_vigencia_inicial",
    "data_vigencia_final",
    "valor_total",
    "status_ata",
    "objeto",
    "quantidade_itens",
    "data_hora_atualizacao",
    "data_hora_inclusao",
    "data_hora_exclusao",
    "ata_excluido",
    "numero_controle_pncp_ata",
    "numero_controle_pncp_compra",
    "id_compra",
)

ARP_ITEM_PK = ("numero_controle_pncp_ata", "numero_item")
ARP_ITEM_COLUMNS = (
    "numero_ata_registro_preco",
    "codigo_unidade_gerenciadora",
    "numero_compra",
    "ano_compra",
    "codigo_modalidade_compra",
    "data_assinatura",
    "data_vigencia_inicial",
    "data_vigencia_final",
    "numero_item",
    "codigo_item",
    "descricao_item",
    "tipo_item",
    "quantidade_homologada_item",
    "classificacao_fornecedor",
    "ni_fornecedor",
    "nome_razao_social_fornecedor",
    "quantidade_homologada_vencedor",
    "valor_unitario",
    "valor_total",
    "maximo_adesao",
    "nome_unidade_gerenciadora",
    "nome_modalidade_compra",
    "id_compra",
    "numero_controle_pncp_compra",
    "data_hora_inclusao",
    "data_hora_atualizacao",
    "quantidade_empenhada",
    "percentual_maior_desconto",
    "situacao_sicaf",
    "data_hora_exclusao",
    "item_excluido",
    "numero_controle_pncp_ata",
    "codigo_pdm",
    "nome_pdm",
)

ARP_UNIDADE_PK = ("numero_ata", "unidade_gerenciadora", "numero_item", "codigo_unidade")
ARP_UNIDADE_COLUMNS = (
    "numero_ata",
    "unidade_gerenciadora",
    "numero_item",
    "codigo_pdm",
    "descricao_item",
    "fornecedor",
    "quantidade_registrada",
    "saldo_adesoes",
    "saldo_remanejamento_empenho",
    "qtd_limite_adesao",
    "qtd_limite_informado_compra",
    "aceita_adesao",
    "data_hora_inclusao",
    "data_hora_atualizacao",
    "data_hora_exclusao",
    "codigo_unidade",
    "nome_unidade",
    "tipo_unidade",
)

ARP_EMPENHO_PK = ("numero_ata", "unidade_gerenciadora", "numero_item", "unidade")
ARP_EMPENHO_COLUMNS = (
    "numero_ata",
    "unidade_gerenciadora",
    "numero_item",
    "unidade",
    "tipo",
    "quantidade_registrada",
    "quantidade_empenhada",
    "saldo_empenho",
    "data_hora_inclusao",
    "data_hora_atualizacao",
)

ARP_ADESAO_PK = ("numero_ata", "unidade_gerenciadora", "unidade_nao_participante")
ARP_ADESAO_COLUMNS = (
    "numero_ata",
    "unidade_gerenciadora",
    "unidade_nao_participante",
    "data_aprovacao_analise",
    "quantidade_aprovada_adesao",
)

CONTRATO_PK = ("numero_controle_pncp_contrato",)
CONTRATO_COLUMNS = (
    "codigo_orgao",
    "nome_orgao",
    "codigo_unidade_gestora",
    "nome_unidade_gestora",
    "codigo_unidade_gestora_origem_contrato",
    "nome_unidade_gestora_origem_contrato",
    "receita_despesa",
    "numero_contrato",
    "codigo_unidade_realizadora_compra",
    "nome_unidade_realizadora_compra",
    "numero_compra",
    "codigo_modalidade_compra",
    "nome_modalidade_compra",
    "codigo_tipo",
    "nome_tipo",
    "codigo_categoria",
    "nome_categoria",
    "codigo_subcategoria",
    "nome_subcategoria",
    "ni_fornecedor",
    "nome_razao_social_fornecedor",
    "processo",
    "objeto",
    "informacoes_complementares",
    "data_vigencia_inicial",
    "data_vigencia_final",
    "valor_global",
    "numero_parcelas",
    "valor_parcela",
    "valor_acumulado",
    "total_despesas_acessorias",
    "data_hora_inclusao",
    "numero_controle_pncp_contrato",
    "numero_controle_pncp_compra",
    "id_compra",
    "data_hora_exclusao",
    "contrato_excluido",
    "unidades_requisitantes",
)

CONTRATO_ITEM_PK = ("numero_controle_pncp_contrato", "numero_item")
CONTRATO_ITEM_COLUMNS = (
    "codigo_orgao",
    "codigo_unidade_gestora",
    "codigo_unidade_gestora_origem_contrato",
    "codigo_unidade_realizadora_compra",
    "codigo_modalidade_compra",
    "numero_contrato",
    "ni_fornecedor",
    "nome_razao_social_fornecedor",
    "processo",
    "data_vigencia_inicial",
    "data_vigencia_final",
    "valor_global",
    "tipo_item",
    "codigo_item",
    "descricao_iitem",
    "quantidade_item",
    "valor_unitario_item",
    "valor_total_item",
    "data_hora_inclusao",
    "numero_controle_pncp_contrato",
    "id_compra",
    "data_hora_exclusao_contrato",
    "contrato_excluido",
    "nome_orgao",
    "nome_unidade_gestora",
    "nome_unidade_gestora_origem_contrato",
    "nome_unidade_realizadora_compra",
    "nome_modalidade_compra",
    "numero_compra",
    "data_hora_exclusao_item",
    "contrato_item_excluido",
    "numero_item",
    "esfera",
    "poder",
    "numero_controle_pncp_compra",
)

FORNECEDOR_PK = ("ni_fornecedor",)
FORNECEDOR_COLUMNS = (
    "ni_fornecedor",
    "ativo",
    "cnpj",
    "cpf",
    "habilitado_licitar",
    "codigo_cnae",
    "nome_cnae",
    "nome_municipio",
    "natureza_juridica_id",
    "natureza_juridica_nome",
    "porte_empresa_id",
    "porte_empresa_nome",
    "nome_razao_social_fornecedor",
    "uf_sigla",
)

INDICADOR_CONSOLIDADO_PK = ("ano_mes_inicio", "ano_mes_fim")
INDICADOR_CONSOLIDADO_COLUMNS = (
    "ano_mes_inicio",
    "ano_mes_fim",
    "total_servicos",
    "total_requisicoes",
    "percentual_sucesso",
    "media_tempo_resposta_ms",
    "total_download_gb",
    "media_download_mes_gb",
)

INDICADOR_PERIODO_PK = ("ano_mes",)
INDICADOR_PERIODO_COLUMNS = (
    "ano_mes",
    "ano",
    "mes",
    "total_servicos",
    "total_requisicoes",
    "percentual_sucesso",
    "media_tempo_resposta_ms",
    "total_download_gb",
    "total_download_mbytes",
)

OCDS_RELEASE_PK = ("ocid", "id")
OCDS_RELEASE_COLUMNS = (
    "ocid",
    "id",
    "date",
    "initiation_type",
    "language",
    "buyer_id",
    "buyer_name",
    "tender_id",
    "tender_title",
    "release_json",
)

ALICE_AVISO_PK = ("ticket_analise",)
ALICE_AVISO_COLUMNS = (
    "ticket_analise",
    "chave_compra",
    "msg_erro",
    "data_solicitacao_analise",
    "data_encerramento_analise",
    "tipo_analise",
    "codigo_status_analise",
    "descricao_status_analise",
)

TABLE_SPECS: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "contratacao": (CONTRATACAO_COLUMNS, CONTRATACAO_PK),
    "contratacao_item": (CONTRATACAO_ITEM_COLUMNS, CONTRATACAO_ITEM_PK),
    "contratacao_resultado": (CONTRATACAO_RESULTADO_COLUMNS, CONTRATACAO_RESULTADO_PK),
    "arp": (ARP_COLUMNS, ARP_PK),
    "arp_item": (ARP_ITEM_COLUMNS, ARP_ITEM_PK),
    "arp_unidade_item": (ARP_UNIDADE_COLUMNS, ARP_UNIDADE_PK),
    "arp_empenho": (ARP_EMPENHO_COLUMNS, ARP_EMPENHO_PK),
    "arp_adesao": (ARP_ADESAO_COLUMNS, ARP_ADESAO_PK),
    "contrato": (CONTRATO_COLUMNS, CONTRATO_PK),
    "contrato_item": (CONTRATO_ITEM_COLUMNS, CONTRATO_ITEM_PK),
    "fornecedor": (FORNECEDOR_COLUMNS, FORNECEDOR_PK),
    "indicador_consolidado": (INDICADOR_CONSOLIDADO_COLUMNS, INDICADOR_CONSOLIDADO_PK),
    "indicador_periodo": (INDICADOR_PERIODO_COLUMNS, INDICADOR_PERIODO_PK),
    "ocds_release": (OCDS_RELEASE_COLUMNS, OCDS_RELEASE_PK),
    "alice_aviso": (ALICE_AVISO_COLUMNS, ALICE_AVISO_PK),
}
