LICITACAO_REQUIRED = ("id_compra",)
LICITACAO_COLUMNS = (
    "id_compra",
    "identificador",
    "numero_processo",
    "uasg",
    "modalidade",
    "nome_modalidade",
    "numero_aviso",
    "situacao_aviso",
    "tipo_pregao",
    "tipo_recurso",
    "nome_responsavel",
    "funcao_responsavel",
    "numero_itens",
    "valor_estimado_total",
    "valor_homologado_total",
    "informacoes_gerais",
    "objeto",
    "endereco_entrega_edital",
    "codigo_municipio_uasg",
    "data_abertura_proposta",
    "data_entrega_edital",
    "data_entrega_proposta",
    "data_publicacao",
    "dt_alteracao",
    "pertence14133",
)

ITEM_LICITACAO_REQUIRED = ("id_compra", "id_compra_item")
ITEM_LICITACAO_COLUMNS = (
    "numero_licitacao",
    "uasg",
    "nome_uasg",
    "modalidade",
    "nome_modalidade",
    "numero_aviso",
    "numero_item_licitacao",
    "codigo_item_material",
    "nome_material",
    "codigo_item_servico",
    "nome_servico",
    "cnpj_fornecedor",
    "nome_fornecedor",
    "quantidade",
    "unidade",
    "descricao_item",
    "beneficio",
    "valor_estimado",
    "decreto_7174",
    "criterio_julgamento",
    "cpf_vencedor",
    "nome_vencedor_pf",
    "sustentavel",
    "dt_alteracao",
    "id_compra",
    "id_compra_item",
)

PREGAO_REQUIRED = ("id_compra",)
PREGAO_COLUMNS = (
    "id_compra",
    "co_processo",
    "co_portaria",
    "co_uasg",
    "no_ausg",
    "co_orgao",
    "no_orgao",
    "numero",
    "ds_situacao_pregao",
    "ds_tipo_pregao",
    "ds_tipo_pregao_compra",
    "tx_objeto",
    "valor_estimado_total",
    "valor_homologado_total",
    "dt_portaria",
    "dt_data_edital",
    "dt_inicio_proposta",
    "dt_fim_proposta",
    "dt_alteracao",
    "dt_encerramento",
    "dt_resultado",
    "pertence14133",
)

ITEM_PREGAO_REQUIRED = ("id_compra", "id_compra_item")
ITEM_PREGAO_COLUMNS = (
    "id_compra",
    "id_compra_item",
    "decreto_7174",
    "situacao_item",
    "descricao_item",
    "descricao_detalhada_item",
    "margem_preferencial",
    "tratamento_diferenciado",
    "quantidade_item",
    "unidade_fornecimento",
    "valor_estimado_item",
    "menor_lance",
    "valor_negociado",
    "valor_homologado_item",
    "fornecedor_vencedor",
    "no_adjudic",
    "no_hom",
    "dt_encerramento",
    "dt_adjudic",
    "dt_hom",
    "dt_alteracao",
)

COMPRA_SEM_REQUIRED = ("id_compra",)
COMPRA_SEM_COLUMNS = (
    "id_compra",
    "co_orgao",
    "co_orgao_superior",
    "co_uasg",
    "no_ausg",
    "co_modalidade_licitacao",
    "ds_lei",
    "nu_processo",
    "qt_total_item",
    "vr_estimado",
    "nu_aviso_licitacao",
    "ds_objeto_licitacao",
    "ds_fundamento_legal",
    "ds_justificativa",
    "no_responsavel_decl_disp",
    "no_cargo_resp_decl_disp",
    "no_responsavel_ratificacao",
    "no_cargo_resp_ratificacao",
    "dt_declaracao_dispensa",
    "dt_ratificacao",
    "dt_publicacao",
    "dt_ano_aviso",
    "dt_alteracao",
    "pertence14133",
)

ITEM_SEM_REQUIRED = ("id_compra", "id_compra_item")
ITEM_SEM_COLUMNS = (
    "co_conjunto_materiais",
    "co_servico",
    "ds_detalhada",
    "in_tipo_fornecedor_vencedor",
    "no_fornecedor_vencedor",
    "no_conjunto_materiais",
    "no_marca_material",
    "no_servico",
    "no_unidade_medida",
    "nu_cnpj_vencedor",
    "nu_cpf_vencedor",
    "qt_material_alt",
    "vr_estimado",
    "in_material_servico",
    "dt_publicacao",
    "id_compra",
    "id_compra_item",
    "co_uasg",
    "co_modalidade_licitacao",
    "no_modalidade_licitacao",
    "nu_aviso_licitacao",
    "dt_ano_aviso_licitacao",
    "nu_inciso",
    "nu_processo",
    "qt_total_item",
    "ds_objeto_licitacao",
    "ds_fundamento_legal",
    "ds_justificativa",
    "nu_cpf_resp_decl_disp",
    "nu_cpf_resp_ratificacao",
    "nu_cpf_resp_publicacao",
    "no_responsavel_decl_disp",
    "no_cargo_resp_decl_disp",
    "no_responsavel_ratificacao",
    "no_cargo_resp_ratificacao",
    "nu_item_material",
    "vr_estimado_item",
    "ds_fabricante",
    "dt_alteracao",
    "co_orgao",
)

RDC_REQUIRED = ("identificador",)
RDC_COLUMNS = (
    "data_abertura_proposta",
    "data_entrega_edital",
    "data_entrega_proposta",
    "data_publicacao",
    "endereco_entrega_edital",
    "forma_de_realizacao_licitacao",
    "funcao_responsavel",
    "identificador",
    "informacoes_gerais",
    "modalidade",
    "nome_responsavel",
    "numero_aviso",
    "numero_itens",
    "numero_processo",
    "objeto",
    "situacao_aviso",
    "tipo_recurso",
    "uasg",
    "orgao_uasg",
    "uf_uasg",
)
