CREATE TABLE contratacao (
id_compra TEXT NOT NULL,
numero_controle_pncp TEXT,
ano_compra_pncp TEXT,
sequencial_compra_pncp TEXT,
orgao_entidade_cnpj TEXT,
orgao_subrogado_cnpj TEXT,
codigo_orgao TEXT,
orgao_entidade_razao_social TEXT,
orgao_subrogado_razao_social TEXT,
orgao_entidade_esfera_id TEXT,
orgao_subrogado_esfera_id TEXT,
orgao_entidade_poder_id TEXT,
orgao_subrogado_poder_id TEXT,
unidade_orgao_codigo_unidade TEXT,
unidade_subrogada_codigo_unidade TEXT,
unidade_orgao_nome_unidade TEXT,
unidade_subrogada_nome_unidade TEXT,
unidade_orgao_uf_sigla TEXT,
unidade_subrogada_uf_sigla TEXT,
unidade_orgao_municipio_nome TEXT,
unidade_subrogada_municipio_nome TEXT,
unidade_orgao_codigo_ibge TEXT,
unidade_subrogada_codigo_ibge TEXT,
numero_compra TEXT,
modalidade_id_pncp TEXT,
codigo_modalidade TEXT,
modalidade_nome TEXT,
srp TEXT,
modo_disputa_id_pncp TEXT,
codigo_modo_disputa TEXT,
amparo_legal_codigo_pncp TEXT,
amparo_legal_nome TEXT,
amparo_legal_descricao TEXT,
informacao_complementar TEXT,
processo TEXT,
objeto_compra TEXT,
existe_resultado TEXT,
orcamento_sigiloso_codigo TEXT,
orcamento_sigiloso_descricao TEXT,
situacao_compra_id_pncp TEXT,
situacao_compra_nome_pncp TEXT,
tipo_instrumento_convocatorio_codigo_pncp TEXT,
tipo_instrumento_convocatorio_nome TEXT,
modo_disputa_nome_pncp TEXT,
valor_total_estimado TEXT,
valor_total_homologado TEXT,
data_inclusao_pncp TEXT,
data_atualizacao_pncp TEXT,
data_publicacao_pncp TEXT,
data_abertura_proposta_pncp TEXT,
data_encerramento_proposta_pncp TEXT,
contratacao_excluida TEXT,
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (id_compra)
);
