CREATE TABLE legado_item_pregao (
id_compra varchar(64) NOT NULL,
id_compra_item varchar(64) NOT NULL,
decreto_7174 varchar(50),
situacao_item varchar(200),
descricao_item TEXT,
descricao_detalhada_item TEXT,
margem_preferencial varchar(200),
tratamento_diferenciado varchar(200),
quantidade_item NUMERIC,
unidade_fornecimento varchar(100),
valor_estimado_item NUMERIC,
menor_lance NUMERIC,
valor_negociado NUMERIC,
valor_homologado_item NUMERIC,
fornecedor_vencedor varchar(200),
no_adjudic varchar(200),
no_hom varchar(200),
dt_encerramento TIMESTAMP,
dt_adjudic TIMESTAMP,
dt_hom TIMESTAMP,
dt_alteracao TIMESTAMP,
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (id_compra, id_compra_item)
);
