CREATE TABLE legado_item_licitacao (
numero_licitacao varchar(64),
uasg BIGINT,
nome_uasg varchar(200),
modalidade BIGINT,
nome_modalidade varchar(200),
numero_aviso BIGINT,
numero_item_licitacao BIGINT,
codigo_item_material BIGINT,
nome_material TEXT,
codigo_item_servico BIGINT,
nome_servico TEXT,
cnpj_fornecedor varchar(20),
nome_fornecedor varchar(200),
quantidade NUMERIC,
unidade varchar(50),
descricao_item TEXT,
beneficio varchar(200),
valor_estimado NUMERIC,
decreto_7174 varchar(50),
criterio_julgamento varchar(200),
cpf_vencedor varchar(20),
nome_vencedor_pf varchar(200),
sustentavel BIGINT,
dt_alteracao TIMESTAMP,
id_compra varchar(64) NOT NULL,
id_compra_item varchar(64) NOT NULL,
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (id_compra, id_compra_item)
);
