CREATE TABLE legado_compra_sem_licitacao (
id_compra varchar(64) PRIMARY KEY,
co_orgao varchar(32),
co_orgao_superior varchar(32),
co_uasg BIGINT,
no_ausg varchar(200),
co_modalidade_licitacao BIGINT,
ds_lei varchar(200),
nu_processo varchar(64),
qt_total_item BIGINT,
vr_estimado NUMERIC,
nu_aviso_licitacao BIGINT,
ds_objeto_licitacao TEXT,
ds_fundamento_legal TEXT,
ds_justificativa TEXT,
no_responsavel_decl_disp varchar(200),
no_cargo_resp_decl_disp varchar(200),
no_responsavel_ratificacao varchar(200),
no_cargo_resp_ratificacao varchar(200),
dt_declaracao_dispensa TIMESTAMP,
dt_ratificacao TIMESTAMP,
dt_publicacao TIMESTAMP,
dt_ano_aviso BIGINT,
dt_alteracao TIMESTAMP,
pertence14133 BOOLEAN,
data_hora_carga TIMESTAMPTZ DEFAULT now()
);
