CREATE TABLE arp (
numero_ata_registro_preco TEXT,
codigo_unidade_gerenciadora TEXT,
nome_unidade_gerenciadora TEXT,
codigo_orgao TEXT,
nome_orgao TEXT,
link_ata_pncp TEXT,
link_compra_pncp TEXT,
numero_compra TEXT,
ano_compra TEXT,
codigo_modalidade_compra TEXT,
nome_modalidade_compra TEXT,
data_assinatura TEXT,
data_vigencia_inicial TEXT,
data_vigencia_final TEXT,
valor_total TEXT,
status_ata TEXT,
objeto TEXT,
quantidade_itens TEXT,
data_hora_atualizacao TEXT,
data_hora_inclusao TEXT,
data_hora_exclusao TEXT,
ata_excluido TEXT,
numero_controle_pncp_ata TEXT NOT NULL,
numero_controle_pncp_compra TEXT,
id_compra TEXT,
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (numero_controle_pncp_ata)
);
