CREATE TABLE legado_pregao (
id_compra varchar(64) PRIMARY KEY,
co_processo varchar(64),
co_portaria varchar(64),
co_uasg BIGINT,
no_ausg varchar(200),
co_orgao BIGINT,
no_orgao varchar(200),
numero BIGINT,
ds_situacao_pregao varchar(200),
ds_tipo_pregao varchar(200),
ds_tipo_pregao_compra varchar(200),
tx_objeto TEXT,
valor_estimado_total NUMERIC,
valor_homologado_total NUMERIC,
dt_portaria TIMESTAMP,
dt_data_edital TIMESTAMP,
dt_inicio_proposta TIMESTAMP,
dt_fim_proposta TIMESTAMP,
dt_alteracao TIMESTAMP,
dt_encerramento TIMESTAMP,
dt_resultado TIMESTAMP,
pertence14133 BOOLEAN,
data_hora_carga TIMESTAMPTZ DEFAULT now()
);
