CREATE TABLE preco_material (
id_compra TEXT NOT NULL,
id_item_compra BIGINT NOT NULL,
numero_item_compra BIGINT,
codigo_item_catalogo BIGINT NOT NULL,
forma varchar(200),
modalidade BIGINT,
criterio_julgamento varchar(200),
descricao_item TEXT,
nome_unidade_medida varchar(200),
sigla_unidade_medida varchar(50),
quantidade NUMERIC,
preco_unitario NUMERIC,
percentual_maior_desconto NUMERIC,
ni_fornecedor varchar(20),
nome_fornecedor varchar(200),
codigo_uasg varchar(20),
nome_uasg varchar(200),
codigo_municipio BIGINT,
municipio varchar(200),
estado varchar(20),
codigo_orgao BIGINT,
nome_orgao varchar(200),
poder varchar(50),
esfera varchar(50),
data_compra varchar(32),
data_hora_atualizacao_compra TIMESTAMP,
data_hora_atualizacao_item TIMESTAMP,
data_resultado varchar(32),
data_hora_atualizacao_uasg TIMESTAMP,
objeto_compra TEXT,
descricao_detalhada_item TEXT,
data_atualizacao_fato TIMESTAMP,
sigla_unidade_fornecimento varchar(50),
nome_unidade_fornecimento varchar(200),
capacidade_unidade_fornecimento NUMERIC,
marca varchar(200),
codigo_classe BIGINT,
nome_classe varchar(200),
id_compra_item varchar(200),
codigo_pdm varchar(50),
nome_pdm varchar(200),
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (id_compra, id_item_compra)
);
