CREATE TABLE contratacao_item (
id_compra TEXT NOT NULL,
id_compra_item TEXT NOT NULL,
id_contratacao_pncp TEXT,
unidade_orgao_codigo_unidade TEXT,
orgao_entidade_cnpj TEXT,
numero_item_pncp TEXT,
numero_item_compra TEXT,
numero_grupo TEXT,
descricao_resumida TEXT,
material_ou_servico TEXT,
material_ou_servico_nome TEXT,
codigo_classe TEXT,
codigo_grupo TEXT,
cod_item_catalogo TEXT,
descricaodetalhada TEXT,
unidade_medida TEXT,
orcamento_sigiloso TEXT,
item_categoria_id_pncp TEXT,
item_categoria_nome TEXT,
criterio_julgamento_id_pncp TEXT,
criterio_julgamento_nome TEXT,
situacao_compra_item TEXT,
situacao_compra_item_nome TEXT,
tipo_beneficio TEXT,
tipo_beneficio_nome TEXT,
incentivo_produtivo_basico TEXT,
quantidade TEXT,
valor_unitario_estimado TEXT,
valor_total TEXT,
tem_resultado TEXT,
cod_fornecedor TEXT,
nome_fornecedor TEXT,
quantidade_resultado TEXT,
valor_unitario_resultado TEXT,
valor_total_resultado TEXT,
data_inclusao_pncp TEXT,
data_atualizacao_pncp TEXT,
data_resultado TEXT,
margem_preferencia_normal TEXT,
percentual_margem_preferencia_normal TEXT,
margem_preferencia_adicional TEXT,
percentual_margem_preferencia_adicional TEXT,
codigo_ncm TEXT,
descricao_ncm TEXT,
numero_controle_pncp_compra TEXT,
codigo_pdm TEXT,
nome_pdm TEXT,
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (id_compra, id_compra_item)
);
