CREATE TABLE pgc_detalhe_catalogo (
codigo_uasg varchar(20) NOT NULL,
nome_uasg varchar(200),
orgao varchar(32) NOT NULL,
numero_artefato BIGINT NOT NULL,
ano_artefato BIGINT NOT NULL,
codigo_estado_artefato BIGINT,
codigo_categoria_artefato BIGINT,
descricao_artefato TEXT,
codigo_tipo_artefato BIGINT,
ordem_dfd BIGINT NOT NULL,
descricao_objeto_dfd TEXT,
nivel_prioridade_dfd BIGINT,
data_prevista_formalizacao_demanda TIMESTAMP,
codigo_area_dfd varchar(50),
tipo_item varchar(50),
item_sustentavel BOOLEAN,
codigo_grupo_material BIGINT,
nome_grupo_material varchar(200),
codigo_classe_material BIGINT,
nome_classe_material varchar(200),
codigo_pdm_material BIGINT,
nome_pdm_material varchar(200),
codigo_secao_servico BIGINT,
nome_secao_servico varchar(200),
codigo_divisao_servico BIGINT,
nome_divisao_servico varchar(200),
codigo_grupo_servico BIGINT,
nome_grupo_servico varchar(200),
codigo_classe_servico BIGINT,
nome_classe_servico varchar(200),
codigo_subclasse_servico BIGINT,
nome_subclasse_servico varchar(200),
codigo_item_catalogo TEXT NOT NULL,
descricao_item_catalogo TEXT,
sigla_unidade_fornecimento varchar(50),
nome_unidade_fornecimento varchar(200),
quantidade_item NUMERIC,
valor_unitario_item NUMERIC,
valor_total_item NUMERIC,
titulo_projeto_compra TEXT,
descricao_projeto_compra TEXT,
ano_pca_projeto_compra BIGINT NOT NULL,
data_inicio_processo_compra TIMESTAMP,
data_fim_processo_compra TIMESTAMP,
duracao_processo_compra BIGINT,
numero_item_pncp BIGINT,
status_contratacao_execucao BIGINT,
data_hora_publicacao_pncp TIMESTAMP,
data_hora_atualizacao_artefato TIMESTAMP,
data_hora_atualizacao_projeto_compra TIMESTAMP,
data_hora_atualizacao_dfd TIMESTAMP,
data_hora_atualizacao_item TIMESTAMP,
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (
    codigo_uasg, numero_artefato, ano_artefato, ordem_dfd,
    codigo_item_catalogo, ano_pca_projeto_compra
)
);
