CREATE TABLE contrato (
codigo_orgao TEXT,
nome_orgao TEXT,
codigo_unidade_gestora TEXT,
nome_unidade_gestora TEXT,
codigo_unidade_gestora_origem_contrato TEXT,
nome_unidade_gestora_origem_contrato TEXT,
receita_despesa TEXT,
numero_contrato TEXT,
codigo_unidade_realizadora_compra TEXT,
nome_unidade_realizadora_compra TEXT,
numero_compra TEXT,
codigo_modalidade_compra TEXT,
nome_modalidade_compra TEXT,
codigo_tipo TEXT,
nome_tipo TEXT,
codigo_categoria TEXT,
nome_categoria TEXT,
codigo_subcategoria TEXT,
nome_subcategoria TEXT,
ni_fornecedor TEXT,
nome_razao_social_fornecedor TEXT,
processo TEXT,
objeto TEXT,
informacoes_complementares TEXT,
data_vigencia_inicial TEXT,
data_vigencia_final TEXT,
valor_global TEXT,
numero_parcelas TEXT,
valor_parcela TEXT,
valor_acumulado TEXT,
total_despesas_acessorias TEXT,
data_hora_inclusao TEXT,
numero_controle_pncp_contrato TEXT NOT NULL,
numero_controle_pncp_compra TEXT,
id_compra TEXT,
data_hora_exclusao TEXT,
contrato_excluido TEXT,
unidades_requisitantes TEXT,
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (numero_controle_pncp_contrato)
);
