CREATE TABLE uasg (
codigo_uasg varchar(20) PRIMARY KEY,
nome_uasg varchar(200) NOT NULL,
uso_sisg BOOLEAN,
adesao_siasg BOOLEAN,
sigla_uf varchar(2),
codigo_municipio BIGINT,
codigo_municipio_ibge BIGINT,
nome_municipio_ibge varchar(200),
codigo_unidade_polo BIGINT,
nome_unidade_polo varchar(200),
codigo_unidade_espelho BIGINT,
nome_unidade_espelho varchar(200),
uasg_cadastradora BOOLEAN,
cnpj_cpf_uasg varchar(20),
codigo_orgao BIGINT,
cnpj_cpf_orgao varchar(20),
cnpj_cpf_orgao_vinculado varchar(20),
cnpj_cpf_orgao_superior varchar(20),
codigo_siorg varchar(32),
status_uasg BOOLEAN,
data_implantacao_sidec TIMESTAMP,
data_hora_movimento TIMESTAMP,
data_hora_carga TIMESTAMPTZ DEFAULT now()
);
