CREATE TABLE arp_item (
numero_ata_registro_preco TEXT,
codigo_unidade_gerenciadora TEXT,
numero_compra TEXT,
ano_compra TEXT,
codigo_modalidade_compra TEXT,
data_assinatura TEXT,
data_vigencia_inicial TEXT,
data_vigencia_final TEXT,
numero_item TEXT NOT NULL,
codigo_item TEXT,
descricao_item TEXT,
tipo_item TEXT,
quantidade_homologada_item TEXT,
classificacao_fornecedor TEXT,
ni_fornecedor TEXT,
nome_razao_social_fornecedor TEXT,
quantidade_homologada_vencedor TEXT,
valor_unitario TEXT,
valor_total TEXT,
maximo_adesao TEXT,
nome_unidade_gerenciadora TEXT,
nome_modalidade_compra TEXT,
id_compra TEXT,
numero_controle_pncp_compra TEXT,
data_hora_inclusao TEXT,
data_hora_atualizacao TEXT,
quantidade_empenhada TEXT,
percentual_maior_desconto TEXT,
situacao_sicaf TEXT,
data_hora_exclusao TEXT,
item_excluido TEXT,
numero_controle_pncp_ata TEXT NOT NULL,
codigo_pdm TEXT,
nome_pdm TEXT,
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (numero_controle_pncp_ata, numero_item)
);
