CREATE TABLE contrato_item (
codigo_orgao TEXT,
codigo_unidade_gestora TEXT,
codigo_unidade_gestora_origem_contrato TEXT,
codigo_unidade_realizadora_compra TEXT,
codigo_modalidade_compra TEXT,
numero_contrato TEXT,
ni_fornecedor TEXT,
nome_razao_social_fornecedor TEXT,
processo TEXT,
data_vigencia_inicial TEXT,
data_vigencia_final TEXT,
valor_global TEXT,
tipo_item TEXT,
codigo_item TEXT,
descricao_iitem TEXT,
quantidade_item TEXT,
valor_unitario_item TEXT,
valor_total_item TEXT,
data_hora_inclusao TEXT,
numero_controle_pncp_contrato TEXT NOT NULL,
id_compra TEXT,
data_hora_exclusao_contrato TEXT,
contrato_excluido TEXT,
nome_orgao TEXT,
nome_unidade_gestora TEXT,
nome_unidade_gestora_origem_contrato TEXT,
nome_unidade_realizadora_compra TEXT,
nome_modalidade_compra TEXT,
numero_compra TEXT,
data_hora_exclusao_item TEXT,
contrato_item_excluido TEXT,
numero_item TEXT NOT NULL,
esfera TEXT,
poder TEXT,
numero_controle_pncp_compra TEXT,
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (numero_controle_pncp_contrato, numero_item)
);
