CREATE TABLE legado_licitacao (
id_compra varchar(64) PRIMARY KEY,
identificador varchar(64),
numero_processo varchar(64),
uasg BIGINT,
modalidade BIGINT,
nome_modalidade varchar(200),
numero_aviso BIGINT,
situacao_aviso varchar(200),
tipo_pregao varchar(100),
tipo_recurso varchar(100),
nome_responsavel varchar(200),
funcao_responsavel varchar(200),
numero_itens BIGINT,
valor_estimado_total NUMERIC,
valor_homologado_total NUMERIC,
informacoes_gerais TEXT,
objeto TEXT,
endereco_entrega_edital TEXT,
codigo_municipio_uasg BIGINT,
data_abertura_proposta TIMESTAMP,
data_entrega_edital TIMESTAMP,
data_entrega_proposta TIMESTAMP,
data_publicacao TIMESTAMP,
dt_alteracao TIMESTAMP,
pertence14133 BOOLEAN,
data_hora_carga TIMESTAMPTZ DEFAULT now()
);
