CREATE TABLE legado_item_sem_licitacao (
co_conjunto_materiais BIGINT,
co_servico BIGINT,
ds_detalhada TEXT,
in_tipo_fornecedor_vencedor varchar(50),
no_fornecedor_vencedor varchar(200),
no_conjunto_materiais TEXT,
no_marca_material varchar(200),
no_servico TEXT,
no_unidade_medida varchar(100),
nu_cnpj_vencedor varchar(20),
nu_cpf_vencedor varchar(20),
qt_material_alt NUMERIC,
vr_estimado NUMERIC,
in_material_servico varchar(50),
dt_publicacao TIMESTAMP,
id_compra varchar(64) NOT NULL,
id_compra_item varchar(64) NOT NULL,
co_uasg BIGINT,
co_modalidade_licitacao BIGINT,
no_modalidade_licitacao varchar(200),
nu_aviso_licitacao BIGINT,
dt_ano_aviso_licitacao BIGINT,
nu_inciso varchar(50),
nu_processo varchar(64),
qt_total_item BIGINT,
ds_objeto_licitacao TEXT,
ds_fundamento_legal TEXT,
ds_justificativa TEXT,
nu_cpf_resp_decl_disp varchar(20),
nu_cpf_resp_ratificacao varchar(20),
nu_cpf_resp_publicacao varchar(20),
no_responsavel_decl_disp varchar(200),
no_cargo_resp_decl_disp varchar(200),
no_responsavel_ratificacao varchar(200),
no_cargo_resp_ratificacao varchar(200),
nu_item_material BIGINT,
vr_estimado_item NUMERIC,
ds_fabricante varchar(200),
dt_alteracao TIMESTAMP,
co_orgao varchar(32),
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (id_compra, id_compra_item)
);
