CREATE TABLE contratacao_resultado (
id_compra_item TEXT NOT NULL,
id_compra TEXT NOT NULL,
id_contratacao_pncp TEXT,
unidade_orgao_codigo_unidade TEXT,
unidade_orgao_uf_sigla TEXT,
numero_item_pncp TEXT,
sequencial_resultado TEXT NOT NULL,
ni_fornecedor TEXT,
tipo_pessoa TEXT,
nome_razao_social_fornecedor TEXT,
codigo_pais TEXT,
indicador_subcontratacao TEXT,
ordem_classificacao_srp TEXT,
quantidade_homologada TEXT,
valor_unitario_homologado TEXT,
valor_total_homologado TEXT,
percentual_desconto TEXT,
situacao_compra_item_resultado_id TEXT,
situacao_compra_item_resultado_nome TEXT,
motivo_cancelamento TEXT,
porte_fornecedor_id TEXT,
porte_fornecedor_nome TEXT,
natureza_juridica_nome TEXT,
natureza_juridica_id TEXT,
data_inclusao_pncp TEXT,
data_atualizacao_pncp TEXT,
data_cancelamento_pncp TEXT,
data_resultado_pncp TEXT,
numero_controle_pncp_compra TEXT,
orgao_entidade_cnpj TEXT,
aplicacao_margem_preferencia TEXT,
amparo_legal_margem_preferencia_id TEXT,
amparo_legal_margem_preferencia_nome TEXT,
aplicacao_beneficio_meepp TEXT,
aplicacao_criterio_desempate TEXT,
amparo_legal_criterio_desempate_id TEXT,
amparo_legal_criterio_desempate_nome TEXT,
moeda_estrangeira_id TEXT,
data_cotacao_moeda_estrangeira TEXT,
valor_nominal_moeda_estrangeira TEXT,
pais_origem_produto_servico_id TEXT,
timezone_cotacao_moeda_estrangeira TEXT,
data_hora_carga TIMESTAMPTZ DEFAULT now(),
PRIMARY KEY (id_compra, id_compra_item, sequencial_resultado)
);
